package impl

import (
	"context"
	"errors"
	"time"

	"CONVERDA/internal/notification/application/service"
	"CONVERDA/internal/notification/domain/entity"
	"CONVERDA/internal/notification/domain/repository"

	"github.com/google/uuid"
)

type groupManager struct {
	repo repository.NotificationGroupRepository
}

func NewGroupManager(repo repository.NotificationGroupRepository) service.GroupManager {
	return &groupManager{repo: repo}
}

func (s *groupManager) CreateGroup(ctx context.Context, envID uuid.UUID, name, key, description string, isDefault bool) (*entity.NotificationGroup, error) {
	// Check if key exists
	existing, err := s.repo.GetByKey(ctx, envID, key)
	if err != nil {
		return nil, err
	}
	if existing != nil {
		return nil, errors.New("group with this key already exists")
	}

	group := &entity.NotificationGroup{
		ID: uuid.New(), // V7 is generated by DB usually if default, but we can generate here if needed. Repo/Model uses V7 default.
		// If I generate here V4, it works.
		// Let's rely on DB or generate V7 here.
		// Using uuid.New() (V4) is fine for now.
		EnvironmentID: envID,
		Name:          name,
		Key:           key,
		Description:   description,
		IsDefault:     isDefault,
		CreatedAt:     time.Now(),
		UpdatedAt:     time.Now(),
	}

	if err := s.repo.Create(ctx, group); err != nil {
		return nil, err
	}
	return group, nil
}

func (s *groupManager) UpdateGroup(ctx context.Context, envID uuid.UUID, id uuid.UUID, name, description string) error {
	group, err := s.repo.GetByID(ctx, id)
	if err != nil {
		return err
	}
	if group == nil {
		return errors.New("group not found")
	}
	if group.EnvironmentID != envID {
		return errors.New("group not found in this environment")
	}

	group.Name = name
	group.Description = description
	group.UpdatedAt = time.Now()

	return s.repo.Update(ctx, group)
}

func (s *groupManager) DeleteGroup(ctx context.Context, envID uuid.UUID, id uuid.UUID) error {
	group, err := s.repo.GetByID(ctx, id)
	if err != nil {
		return err
	}
	if group == nil {
		return nil // Already deleted
	}
	if group.EnvironmentID != envID {
		return errors.New("group not found in this environment")
	}

	return s.repo.Delete(ctx, id)
}

func (s *groupManager) GetGroup(ctx context.Context, envID uuid.UUID, id uuid.UUID) (*entity.NotificationGroup, error) {
	group, err := s.repo.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if group != nil && group.EnvironmentID != envID {
		return nil, nil // Hide if not in env
	}
	return group, nil
}

func (s *groupManager) ListGroups(ctx context.Context, envID uuid.UUID, limit, offset int) ([]*entity.NotificationGroup, int64, error) {
	return s.repo.List(ctx, envID, limit, offset)
}

func (s *groupManager) GetByKey(ctx context.Context, envID uuid.UUID, key string) (*entity.NotificationGroup, error) {
	return s.repo.GetByKey(ctx, envID, key)
}
