package impl

import (
	"context"
	"fmt"
	"time"

	"CONVERDA/internal/notification/application/service"
	domain "CONVERDA/internal/notification/domain"
	"CONVERDA/internal/notification/domain/entity"
	"CONVERDA/internal/notification/domain/repository"

	"github.com/google/uuid"
)

type groupManager struct {
	repo repository.NotificationGroupRepository
	uow  repository.NotificationUnitOfWork
}

func NewGroupManager(repo repository.NotificationGroupRepository, uow repository.NotificationUnitOfWork) service.GroupManager {
	return &groupManager{repo: repo, uow: uow}
}

func (s *groupManager) CreateGroup(ctx context.Context, envID uuid.UUID, name, key, description string, isDefault bool) (*entity.NotificationGroup, error) {
	// Check if key exists
	existing, err := s.repo.GetByKey(ctx, envID, key)
	if err != nil {
		return nil, fmt.Errorf("failed to check group key: %w", err)
	}
	if existing != nil {
		return nil, domain.ErrGroupDuplicateKey
	}

	group := &entity.NotificationGroup{
		ID: uuid.New(), // V7 is generated by DB usually if default, but we can generate here if needed. Repo/Model uses V7 default.
		// If I generate here V4, it works.
		// Let's rely on DB or generate V7 here.
		// Using uuid.New() (V4) is fine for now.
		EnvironmentID: envID,
		Name:          name,
		Key:           key,
		Description:   description,
		IsDefault:     isDefault,
		CreatedAt:     time.Now(),
		UpdatedAt:     time.Now(),
	}

	if err := s.uow.Execute(ctx, func(tx repository.NotificationTxRepository) error {
		// Check if key exists again within transaction
		existing, err := tx.Groups().GetByKey(ctx, envID, key)
		if err != nil {
			return err
		}
		if existing != nil {
			return domain.ErrGroupDuplicateKey
		}
		return tx.Groups().Create(ctx, group)
	}); err != nil {
		return nil, err
	}
	return group, nil
}

func (s *groupManager) UpdateGroup(ctx context.Context, envID uuid.UUID, id uuid.UUID, name, description string) error {
	return s.uow.Execute(ctx, func(tx repository.NotificationTxRepository) error {
		group, err := tx.Groups().GetByID(ctx, id)
		if err != nil {
			return fmt.Errorf("failed to fetch group %s: %w", id, err)
		}
		if group == nil {
			return domain.ErrGroupNotFound
		}
		if group.EnvironmentID != envID {
			return domain.ErrGroupNotInEnv
		}

		group.Name = name
		group.Description = description
		group.UpdatedAt = time.Now()

		return tx.Groups().Update(ctx, group)
	})
}

func (s *groupManager) DeleteGroup(ctx context.Context, envID uuid.UUID, id uuid.UUID) error {
	return s.uow.Execute(ctx, func(tx repository.NotificationTxRepository) error {
		group, err := tx.Groups().GetByID(ctx, id)
		if err != nil {
			return fmt.Errorf("failed to fetch group %s: %w", id, err)
		}
		if group == nil {
			return nil // Already deleted
		}
		if group.EnvironmentID != envID {
			return domain.ErrGroupNotInEnv
		}

		return tx.Groups().Delete(ctx, id)
	})
}

func (s *groupManager) GetGroup(ctx context.Context, envID uuid.UUID, id uuid.UUID) (*entity.NotificationGroup, error) {
	group, err := s.repo.GetByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch group %s: %w", id, err)
	}
	if group != nil && group.EnvironmentID != envID {
		return nil, nil // Hide if not in env
	}
	return group, nil
}

func (s *groupManager) ListGroups(ctx context.Context, envID uuid.UUID, limit, offset int) ([]*entity.NotificationGroup, int64, error) {
	groups, total, err := s.repo.List(ctx, envID, limit, offset)
	if err != nil {
		return nil, 0, fmt.Errorf("failed to list groups for env %s: %w", envID, err)
	}
	return groups, total, nil
}

func (s *groupManager) GetByKey(ctx context.Context, envID uuid.UUID, key string) (*entity.NotificationGroup, error) {
	group, err := s.repo.GetByKey(ctx, envID, key)
	if err != nil {
		return nil, fmt.Errorf("failed to get group by key %s for env %s: %w", key, envID, err)
	}
	return group, nil
}
